# Generated by Django 6.0.2 on 2026-02-14 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('title_hi', models.CharField(max_length=300, verbose_name='Title (Hindi)')),
                ('code', models.CharField(help_text='e.g., POL-SRC', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Chapters',
                'ordering': ['subject', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_hi', models.CharField(max_length=200, verbose_name='Name (Hindi)')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('foundation', 'Foundation'), ('advanced', 'Advanced'), ('up_special', 'UP Special'), ('csat', 'CSAT')], max_length=20)),
                ('icon', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(help_text='e.g., POL-SRC-001', max_length=50, unique=True)),
                ('stem', models.TextField(verbose_name='Question Text')),
                ('stem_hi', models.TextField(blank=True, verbose_name='Question Text (Hindi)')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('explanation', models.TextField()),
                ('explanation_hi', models.TextField(blank=True, verbose_name='Explanation (Hindi)')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('exam_source', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('question_type', models.CharField(choices=[('factual', 'Factual'), ('conceptual', 'Conceptual'), ('application', 'Application')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.chapter')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('term_hi', models.CharField(max_length=200, verbose_name='Term (Hindi)')),
                ('definition', models.TextField()),
                ('definition_hi', models.TextField(verbose_name='Definition (Hindi)')),
                ('related_questions', models.ManyToManyField(blank=True, related_name='key_terms', to='content.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_terms', to='content.subject')),
            ],
            options={
                'verbose_name_plural': 'Key Terms',
                'ordering': ['term'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content.subject'),
        ),
    ]
