# Generated by Django 6.0.2 on 2026-03-01 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name in English', max_length=40, unique=True)),
                ('name_hi', models.CharField(blank=True, default='', help_text='Display name in Hindi', max_length=60)),
                ('slug', models.SlugField(help_text='URL-safe identifier', unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text='Emoji icon', max_length=5)),
                ('description', models.TextField(blank=True, default='', help_text='1-2 sentence description')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (lower first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show to students?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'content_subject',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name in English', max_length=50)),
                ('name_hi', models.CharField(blank=True, default='', help_text='Display name in Hindi', max_length=80)),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=60, unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text='Emoji icon', max_length=5)),
                ('description', models.TextField(blank=True, default='', help_text='1-2 sentence description')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within subject')),
                ('is_active', models.BooleanField(default=True, help_text='Show to students?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(help_text='Parent subject', on_delete=django.db.models.deletion.PROTECT, related_name='units', to='content.subject')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'content_unit',
                'ordering': ['subject', 'sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('subject', 'name'), name='unique_unit_per_subject')],
            },
        ),
    ]
