# Generated by Django 6.0.2 on 2026-02-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='title_hi',
        ),
        migrations.RemoveField(
            model_name='keyterm',
            name='definition_hi',
        ),
        migrations.RemoveField(
            model_name='keyterm',
            name='term_hi',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_hi',
        ),
        migrations.RemoveField(
            model_name='question',
            name='stem_hi',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name_hi',
        ),
    ]
