# Generated by Django 6.0.2 on 2026-03-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_mainspyq_evolve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainspyq',
            name='legacy_code',
            field=models.CharField(help_text='e.g. UPM24-GS1-HIST-IN-R-Q01', max_length=30, unique=True),
        ),
    ]
