# Generated by Django 6.0.2 on 2026-03-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_mainspyq_legacy_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=180, help_text='Exam duration in minutes'),
        ),
        migrations.AddField(
            model_name='paper',
            name='exam_stage',
            field=models.CharField(choices=[('prelims', 'Prelims'), ('mains', 'Mains'), ('both', 'Both')], default='mains', help_text='Prelims / Mains / Both', max_length=10),
        ),
        migrations.AddField(
            model_name='paper',
            name='introduced_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year this paper was introduced', null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_qualifying',
            field=models.BooleanField(default=False, help_text='Is this a qualifying paper?'),
        ),
        migrations.AddField(
            model_name='paper',
            name='mains_overlap',
            field=models.JSONField(blank=True, default=list, help_text='List of related mains paper short_names'),
        ),
        migrations.AddField(
            model_name='paper',
            name='negative_marking',
            field=models.BooleanField(default=False, help_text='Does this paper have negative marking?'),
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_data',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible metadata (sections, marks breakup, etc.)'),
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('objective', 'Objective'), ('subjective', 'Subjective'), ('essay', 'Essay'), ('language', 'Language')], default='subjective', help_text='Objective / Subjective / Essay / Language', max_length=12),
        ),
        migrations.AddField(
            model_name='paper',
            name='syllabus_topics',
            field=models.JSONField(blank=True, default=list, help_text='List of syllabus topics'),
        ),
        migrations.AddField(
            model_name='paper',
            name='total_marks',
            field=models.PositiveIntegerField(default=0, help_text='Maximum marks for this paper'),
        ),
        migrations.AddField(
            model_name='paper',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, help_text='Total questions in paper'),
        ),
    ]
