# Generated by Django 6.0.2 on 2026-03-01 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_paper_enrich'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Fundamental Rights', max_length=200)),
                ('name_hi', models.CharField(blank=True, default='', help_text='Display name in Hindi', max_length=300)),
                ('code', models.CharField(help_text='Short code e.g. FR, DPSP, CA', max_length=20)),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='1-2 sentence description')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within unit')),
                ('question_count', models.PositiveIntegerField(default=0, help_text='Denormalized count for speed')),
                ('is_active', models.BooleanField(default=True, help_text='Show to students?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(help_text='Parent unit', on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='content.unit')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'db_table': 'content_chapter',
                'ordering': ['unit', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='mainspyq',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Linked chapter (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mains_pyqs', to='content.chapter'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('unit', 'name'), name='unique_chapter_per_unit'),
        ),
    ]
