# Generated by Django 6.0.2 on 2026-03-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_chapter_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Right to Equality (Art. 14-18)', max_length=200)),
                ('name_hi', models.CharField(blank=True, default='', help_text='Display name in Hindi', max_length=300)),
                ('code', models.CharField(blank=True, default='', help_text='Short code', max_length=20)),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='1-2 sentence description')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within chapter')),
                ('is_active', models.BooleanField(default=True, help_text='Show to students?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(help_text='Parent chapter', on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='content.chapter')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'content_topic',
                'ordering': ['chapter', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Abolition of Untouchability (Art. 17)', max_length=200)),
                ('name_hi', models.CharField(blank=True, default='', help_text='Display name in Hindi', max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within topic')),
                ('is_active', models.BooleanField(default=True, help_text='Show to students?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(help_text='Parent topic', on_delete=django.db.models.deletion.PROTECT, related_name='subtopics', to='content.topic')),
            ],
            options={
                'verbose_name': 'Sub-Topic',
                'verbose_name_plural': 'Sub-Topics',
                'db_table': 'content_subtopic',
                'ordering': ['topic', 'sort_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('chapter', 'name'), name='unique_topic_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='subtopic',
            constraint=models.UniqueConstraint(fields=('topic', 'name'), name='unique_subtopic_per_topic'),
        ),
    ]
