# Generated by Django 6.0.2 on 2026-03-01 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_topic_subtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Section A, Part I - Indian History', max_length=100)),
                ('short_name', models.CharField(help_text='e.g. SEC-A', max_length=20)),
                ('slug', models.SlugField(help_text='URL-safe identifier', unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='1-2 sentence description')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within paper')),
                ('marks', models.PositiveIntegerField(default=0, help_text='Total marks for this part')),
                ('question_count', models.PositiveIntegerField(default=0, help_text='Denormalized count for speed')),
                ('is_active', models.BooleanField(default=True, help_text='Show to students?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(help_text='Parent paper', on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='content.paper')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'db_table': 'content_part',
                'ordering': ['paper', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='mainspyq',
            name='part',
            field=models.ForeignKey(blank=True, help_text='Linked part/section (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='content.part'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('paper', 'name'), name='unique_part_per_paper'),
        ),
    ]
