# Generated by Django 6.0.2 on 2026-03-01 17:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_part_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrelimsPYQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question_id', models.CharField(help_text='e.g. UP-PRE-POL-2024-042', max_length=30, unique=True)),
                ('stem', models.TextField(help_text='Question text')),
                ('stem_hi', models.TextField(blank=True, default='', help_text='Question text in Hindi')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Correct option: A, B, C, or D', max_length=1)),
                ('explanation', models.TextField(blank=True, default='', help_text='Why the answer is correct')),
                ('explanation_hi', models.TextField(blank=True, default='', help_text='Explanation in Hindi')),
                ('teaching_note', models.TextField(blank=True, default='', help_text='Deeper context for learning')),
                ('mnemonic', models.TextField(blank=True, default='', help_text='Memory aid')),
                ('common_mistake', models.TextField(blank=True, default='', help_text='Common wrong reasoning')),
                ('exam_tip', models.TextField(blank=True, default='', help_text='Exam strategy tip')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Unknown', 'Unknown')], default='Medium', max_length=10)),
                ('exam_source', models.CharField(default='UPPCS', help_text='e.g. UPPCS, BPSC, UPSC', max_length=50)),
                ('year', models.PositiveIntegerField(help_text='Year the question appeared', validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2026)])),
                ('tags', models.TextField(blank=True, default='', help_text='Comma-separated tags')),
                ('blooms_level', models.PositiveIntegerField(default=1, help_text="Bloom's taxonomy level 1-6", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('concept_cluster', models.CharField(blank=True, default='', max_length=100)),
                ('repeat_frequency', models.PositiveIntegerField(default=0, help_text='How many times repeated')),
                ('is_free', models.BooleanField(default=True, help_text='Available to free-tier users?')),
                ('is_active', models.BooleanField(default=True, help_text='Show to students?')),
                ('stem_length', models.PositiveIntegerField(default=0, help_text='Character count of stem')),
                ('option_avg_length', models.PositiveIntegerField(default=0, help_text='Average char count of options')),
                ('estimated_time_seconds', models.PositiveIntegerField(default=72, help_text='Estimated solve time')),
                ('times_attempted', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('avg_time_taken', models.FloatField(default=0.0, help_text='Average time in seconds')),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('batch_id', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prelims_pyqs', to='content.chapter')),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prelims_questions', to='content.examsession')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prelims_questions', to='content.paper')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prelims_pyqs', to='content.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prelims_pyqs', to='content.topic')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prelims_pyqs', to='content.unit')),
            ],
            options={
                'verbose_name': 'Prelims PYQ',
                'verbose_name_plural': 'Prelims PYQs',
                'db_table': 'content_prelims_pyq',
                'ordering': ['exam_session', 'subject', 'question_id'],
            },
        ),
    ]
