# Generated by Django 6.0.2 on 2026-03-01 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_prelims_pyq'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainspyq',
            name='fact_code',
            field=models.CharField(blank=True, default='', help_text='Fact classification code', max_length=20),
        ),
        migrations.AddField(
            model_name='mainspyq',
            name='tag_code',
            field=models.CharField(blank=True, default='', help_text='Tag classification code', max_length=50),
        ),
        migrations.AddField(
            model_name='mainspyq',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Linked topic (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mains_pyqs_by_topic', to='content.topic'),
        ),
        migrations.AlterField(
            model_name='mainspyq',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Linked chapter (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mains_pyqs_by_chapter', to='content.chapter'),
        ),
        migrations.AlterField(
            model_name='mainspyq',
            name='part',
            field=models.ForeignKey(blank=True, help_text='Linked part/section (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mains_pyqs_by_part', to='content.part'),
        ),
    ]
