# Generated by Django 6.0.2 on 2026-03-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_mainspyq_topic_factcode_tagcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelimspyq',
            name='repeat_count',
            field=models.PositiveIntegerField(default=1, help_text='How many times this question appeared across exams'),
        ),
        migrations.CreateModel(
            name='QuestionAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_source', models.CharField(help_text='Exam family: UPPCS, MPPCS, UKPCS etc.', max_length=50)),
                ('exam_name', models.CharField(help_text='Full name: U.P. Lower Sub. (Pre)', max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('question_number', models.PositiveIntegerField(blank=True, help_text='Serial number in that paper: Q1, Q47 etc.', null=True)),
                ('is_primary', models.BooleanField(default=True, help_text='True = first time this question appeared')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='content.prelimspyq')),
            ],
            options={
                'verbose_name': 'Question Appearance',
                'verbose_name_plural': 'Question Appearances',
                'db_table': 'content_question_appearance',
                'ordering': ['question', 'year'],
                'constraints': [models.UniqueConstraint(fields=('question', 'year', 'exam_source'), name='unique_question_exam_year')],
            },
        ),
    ]
