# Generated by Django 6.0.2 on 2026-03-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_add_question_appearance_bridge_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name: U.P. Lower Subordinate (Prelims)', max_length=100, unique=True)),
                ('short_name', models.CharField(help_text='Short: UP Lower Sub Pre', max_length=30)),
                ('exam_family', models.CharField(choices=[('UPPCS', 'UP PCS'), ('UKPCS', 'Uttarakhand PCS'), ('MPPCS', 'Madhya Pradesh PCS'), ('BPSC', 'Bihar PCS'), ('RAS', 'Rajasthan RAS'), ('IAS', 'UPSC IAS'), ('OTHER', 'Other')], help_text='UPPCS, MPPCS etc.', max_length=20)),
                ('exam_stage', models.CharField(choices=[('prelims', 'Prelims'), ('mains', 'Mains'), ('interview', 'Interview')], help_text='prelims, mains', max_length=20)),
                ('state', models.CharField(blank=True, default='', help_text='Uttar Pradesh, Madhya Pradesh etc.', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exam Source',
                'verbose_name_plural': 'Exam Sources',
                'db_table': 'content_exam_source',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MicroTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_hi', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_topic', models.ForeignKey(help_text='Parent sub-topic', on_delete=django.db.models.deletion.PROTECT, related_name='microtopics', to='content.subtopic')),
            ],
            options={
                'verbose_name': 'Micro-Topic',
                'verbose_name_plural': 'Micro-Topics',
                'db_table': 'content_microtopic',
                'ordering': ['sub_topic', 'sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('sub_topic', 'name'), name='unique_subtopic_microtopic')],
            },
        ),
    ]
