# Generated by Django 6.0.2 on 2026-03-07 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_add_microtopic_and_examsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelimspyq',
            name='exam_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prelims_questions', to='content.examsession'),
        ),
        migrations.AlterField(
            model_name='prelimspyq',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prelims_questions', to='content.paper'),
        ),
        migrations.AlterField(
            model_name='prelimspyq',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prelims_pyqs', to='content.subject'),
        ),
    ]
