# Generated by Django 6.0.2 on 2026-03-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_make_prelims_fks_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelimspyq',
            name='option_a',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='prelimspyq',
            name='option_b',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='prelimspyq',
            name='option_c',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='prelimspyq',
            name='option_d',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='prelimspyq',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ok', 'OK'), ('needs_review', 'Needs Review'), ('parse_error_no_options', 'Parse Error (No Options)'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=25),
        ),
    ]
