# Generated by Django 6.0.2 on 2026-03-01 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='e.g. T24, T28', max_length=10, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('session', models.CharField(help_text='e.g. S2, S3', max_length=10)),
                ('group', models.CharField(help_text='e.g. Group A: Syllabus Hierarchy', max_length=100)),
                ('module', models.CharField(blank=True, default='', help_text='e.g. M1, M2', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower = higher priority')),
                ('depends_on', models.CharField(blank=True, default='', help_text='e.g. T25,T26', max_length=200)),
                ('models_created', models.TextField(blank=True, default='', help_text='e.g. Chapter, Topic, SubTopic')),
                ('files_changed', models.TextField(blank=True, default='', help_text='e.g. content/models.py, content/admin.py')),
                ('notes', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Build Task',
                'verbose_name_plural': 'Build Tasks',
                'db_table': 'tracker_task',
                'ordering': ['session', 'task_id'],
            },
        ),
        migrations.CreateModel(
            name='BuildSubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_id', models.CharField(help_text='e.g. T28B, T28C', max_length=10, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('depends_on', models.CharField(blank=True, default='', help_text='e.g. T28B,T28C', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tracker.buildtask')),
            ],
            options={
                'verbose_name': 'Build Sub-Task',
                'verbose_name_plural': 'Build Sub-Tasks',
                'db_table': 'tracker_subtask',
                'ordering': ['task', 'subtask_id'],
            },
        ),
    ]
